# Generated by Django 3.1.5 on 2021-01-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=5)),
                ('currency_symbol', models.CharField(help_text='The symbol used for this currency.', max_length=8)),
                ('int_curr_symbol', models.CharField(help_text='The symbol used for this currency for international formatting.', max_length=8)),
                ('p_cs_precedes', models.BooleanField(default=True, help_text='Whether the currency symbol precedes positive values')),
                ('n_cs_precedes', models.BooleanField(default=True, help_text='Whether the currency symbol precedes negative values.')),
                ('p_sep_by_space', models.BooleanField(default=True, help_text='Whether the currency symbol is separated from positive values by a space.')),
                ('n_sep_by_space', models.BooleanField(default=True, help_text='Whether the currency symbol is separated from negative values by a space.')),
                ('mon_decimal_point', models.CharField(help_text='The character used for decimal points.', max_length=1)),
                ('mon_thousands_sep', models.CharField(help_text='The character used for separating groups of numbers.', max_length=1)),
                ('mon_grouping', models.PositiveSmallIntegerField(default=3, help_text='The number of digits per groups.')),
                ('frac_digits', models.PositiveSmallIntegerField(default=2, help_text='The number of digits following the decimal place. Use 0 if this is a non-decimal currency.')),
                ('int_frac_digits', models.PositiveSmallIntegerField(default=2, help_text='The number of digits following the decimal place for international formatting. Use 0 if this is a non-decimal currency.')),
                ('positive_sign', models.CharField(default='', help_text='The symbol to use for the positive sign.', max_length=1)),
                ('negative_sign', models.CharField(default='-', help_text='The symbol to use for the negative sign.', max_length=1)),
                ('p_sign_posn', models.CharField(choices=[('0', 'Currency and value are surrounded by parentheses.'), ('1', 'The sign should precede the value and currency symbol.'), ('2', 'The sign should follow the value and currency symbol.'), ('3', 'The sign should immediately precede the value.'), ('4', 'The sign should immediately follow the value.')], default='0', help_text='How the positive sign should be positioned relative to the currency symbol and value.', max_length=1)),
                ('n_sign_posn', models.CharField(choices=[('0', 'Currency and value are surrounded by parentheses.'), ('1', 'The sign should precede the value and currency symbol.'), ('2', 'The sign should follow the value and currency symbol.'), ('3', 'The sign should immediately precede the value.'), ('4', 'The sign should immediately follow the value.')], default='0', help_text='How the negative sign should be positioned relative to the currency symbol and value.', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Payment Currencies',
            },
        ),
        migrations.AddField(
            model_name='plancost',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.paymentcurrency', verbose_name='currency'),
        ),
    ]
