# Generated by Django 3.1.5 on 2021-01-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_add_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=4)),
                ('currency_symbol', models.CharField(max_length=8)),
                ('int_curr_symbol', models.CharField(max_length=8)),
                ('p_cs_precedes', models.BooleanField(default=True)),
                ('n_cs_precedes', models.BooleanField(default=True)),
                ('p_sep_by_space', models.BooleanField(default=True)),
                ('n_sep_by_space', models.BooleanField(default=True)),
                ('mon_decimal_point', models.CharField(max_length=1)),
                ('mon_thousands_sep', models.CharField(max_length=1)),
                ('mon_grouping', models.PositiveSmallIntegerField(default=3)),
                ('frac_digits', models.PositiveSmallIntegerField(default=2)),
                ('int_frac_digits', models.PositiveSmallIntegerField(default=2)),
                ('positive_sign', models.CharField(default='', max_length=1)),
                ('negative_sign', models.CharField(default='-', max_length=1)),
                ('p_sign_posn', models.CharField(choices=[('0', 'Currency and value are surrounded by parentheses.'), ('1', 'The sign should precede the value and currency symbol.'), ('2', 'The sign should follow the value and currency symbol.'), ('3', 'The sign should immediately precede the value.'), ('4', 'The sign should immediately follow the value.')], default='0', max_length=1)),
                ('n_sign_posn', models.CharField(choices=[('0', 'Currency and value are surrounded by parentheses.'), ('1', 'The sign should precede the value and currency symbol.'), ('2', 'The sign should follow the value and currency symbol.'), ('3', 'The sign should immediately precede the value.'), ('4', 'The sign should immediately follow the value.')], default='0', max_length=1)),
            ],
        ),
    ]
