# Generated by Django 3.1.5 on 2021-01-12 10:37

from django.db import migrations
from subscriptions.currency import CURRENCY

def migrate_defaults(apps, schema_editor):
    model = apps.get_model('subscriptions', 'PaymentCurrency')
    for locale, data in CURRENCY.items():
        model.objects.create(
            locale=locale,
            **data
        )

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20210112_1035'),
    ]

    operations = [
        migrations.RunPython(migrate_defaults)
    ]
