# Generated by Django 3.1.5 on 2021-01-12 08:09

from django.db import migrations, models
from subscriptions.currency import CURRENCY, Currency


def migrate_defaults(apps, schema_editor):
    model = apps.get_model('subscriptions', 'PaymentCurrency')
    for locale, data in CURRENCY.items():
        model.objects.create(
            locale=locale,
            **data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_paymentcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcurrency',
            name='locale',
            field=models.CharField(max_length=5),
        ),
        migrations.RunPython(migrate_defaults)
    ]
