# Generated by Django 3.1.5 on 2021-01-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20210112_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentcurrency',
            options={'verbose_name_plural': 'Payment Currencies'},
        ),
        migrations.AddField(
            model_name='plancost',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.paymentcurrency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='currency_symbol',
            field=models.CharField(help_text='The symbol used for this currency.', max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='frac_digits',
            field=models.PositiveSmallIntegerField(default=2, help_text='The number of digits following the decimal place. Use 0 if this is a non-decimal currency.'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='int_curr_symbol',
            field=models.CharField(help_text='The symbol used for this currency for international formatting.', max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='int_frac_digits',
            field=models.PositiveSmallIntegerField(default=2, help_text='The number of digits following the decimal place for international formatting. Use 0 if this is a non-decimal currency.'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='mon_decimal_point',
            field=models.CharField(help_text='The character used for decimal points.', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='mon_grouping',
            field=models.PositiveSmallIntegerField(default=3, help_text='The number of digits per groups.'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='mon_thousands_sep',
            field=models.CharField(help_text='The character used for separating groups of numbers.', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='n_cs_precedes',
            field=models.BooleanField(default=True, help_text='Whether the currency symbol precedes negative values.'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='n_sep_by_space',
            field=models.BooleanField(default=True, help_text='Whether the currency symbol is separated from negative values by a space.'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='n_sign_posn',
            field=models.CharField(choices=[('0', 'Currency and value are surrounded by parentheses.'), ('1', 'The sign should precede the value and currency symbol.'), ('2', 'The sign should follow the value and currency symbol.'), ('3', 'The sign should immediately precede the value.'), ('4', 'The sign should immediately follow the value.')], default='0', help_text='How the negative sign should be positioned relative to the currency symbol and value.', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='negative_sign',
            field=models.CharField(default='-', help_text='The symbol to use for the negative sign.', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='p_cs_precedes',
            field=models.BooleanField(default=True, help_text='Whether the currency symbol precedes positive values'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='p_sep_by_space',
            field=models.BooleanField(default=True, help_text='Whether the currency symbol is separated from positive values by a space.'),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='p_sign_posn',
            field=models.CharField(choices=[('0', 'Currency and value are surrounded by parentheses.'), ('1', 'The sign should precede the value and currency symbol.'), ('2', 'The sign should follow the value and currency symbol.'), ('3', 'The sign should immediately precede the value.'), ('4', 'The sign should immediately follow the value.')], default='0', help_text='How the positive sign should be positioned relative to the currency symbol and value.', max_length=1),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='positive_sign',
            field=models.CharField(default='', help_text='The symbol to use for the positive sign.', max_length=1),
        ),
    ]
