# Generated by Django 3.1.5 on 2021-01-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20210112_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcurrency',
            name='locale',
            field=models.CharField(max_length=5),
        ),
    ]
