# Generated by Django 3.1.5 on 2021-01-18 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_auto_20210112_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlistdetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_list_details', to='subscriptions.plancost'),
        ),
    ]
