# Generated by Django 3.1.5 on 2021-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_auto_20210118_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
