# Generated by Django 3.1.5 on 2021-01-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_plancost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='transaction_type',
            field=models.CharField(default='P', max_length=2),
        ),
    ]
