# Generated by Django 3.1.5 on 2021-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_auto_20210120_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlistdetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
