# Generated by Django 3.1.5 on 2021-01-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_planlistdetail_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('P', 'Payment'), ('R', 'Refund'), ('C', 'Cancellation')], default='P', max_length=2),
        ),
    ]
