# Generated by Django 3.1.5 on 2021-02-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20210121_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='renewal_status',
            field=models.CharField(choices=[('R', 'Running'), ('T', 'Retrying subscription renewal'), ('F', 'Failed')], default='R', max_length=1),
        ),
    ]
