# Generated by Django 3.1.5 on 2021-01-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20210121_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancost',
            name='recurrence_unit',
            field=models.CharField(choices=[(0, 'once'), (1, 'second'), (2, 'minute'), (3, 'hour'), (4, 'day'), (5, 'week'), (6, 'month'), (7, 'year')], default=6, max_length=1),
        ),
    ]
