# Generated by Django 3.1.5 on 2021-02-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_usersubscription_renewal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.PositiveSmallIntegerField()),
                ('retry_offset', models.PositiveSmallIntegerField(help_text='Number of days in which the payment is to be retried')),
            ],
            options={
                'verbose_name_plural': 'Payment Retries',
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='retry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.paymentretry', verbose_name='retry'),
        ),
    ]
