# Generated by Django 3.1.5 on 2021-02-03 13:13

from django.db import migrations


def migrate_defaults(apps, _):
    model = apps.get_model('subscriptions', 'PaymentRetry')

    days = [1, 3, 5, 7]

    ctr = 1

    for offset in days:
        model.objects.create(
            iteration=ctr,
            retry_offset=offset
        )
        ctr += 1


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20210203_1311'),
    ]

    operations = [
        migrations.RunPython(migrate_defaults)
    ]
